name: K6 Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: '0 11 * * *'  

jobs:
  k6-load-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Grafana K6 Setup
      uses: grafana/setup-k6-action@v1

    - name: Grafana K6 Execution
      uses: grafana/run-k6-action@v1
      env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_GRAFANA_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_GRAFANA_CLOUD_PROJECT_ID }}
      with:
          path: |
            ./scripts/check-threshold-with-stages-github-actions-cloud.js
          cloud-run-locally: false

    - name: Move k6 report to reports folder
      run: |
         ls && mkdir reports && mv index.html reports     

    - name: Upload k6 report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: k6-report
        path: reports
        
    - name: Publish K6 Report
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: reports