name: K6 Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'  

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: grafana/setup-k6-action@v1
    - uses: grafana/run-k6-action@v1
      env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_GRAFANA_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_GRAFANA_CLOUD_PROJECT_ID }}
      with:
          path: |
            ./scripts/check-threshold-with-stages-github-actions-cloud.js
          cloud-run-locally: false
          cloud-comment-on-pr: true

    - name: Upload k6 report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: k6-report
        path: ./reports/k6-report.html 
        
    - name: Download k6 report
      if: always()
      uses: actions/download-artifact@v4
      with:
        name: k6-report
        path: ./reports/k6-report.html    